# Sample requirements file.

# Each package gets its own section. Hopefully the package you are building
# only needs name and version, but there are several other options.

- name: astropy-stable
  # THIS WILL GET UPLOADED AS astropy
  version: '1.2.2'
  setup_options: '--offline --single-version-externally-managed --record=foo.txt'
  numpy_compiled_extensions: true

  # Continuum builds astropy for the latest numpy on py2 and py3. The
  # affiliated package template includes builds against older numpy
  # on python 2.7, so we'll build those.
  python: '2.7*'  # if omitted, no restriction on python builds.

  # Since we only need these for CI, only build on linux.
  excluded_platforms:
    - 'win-64'
    - 'osx-64'

- name: astropy-lts
  # THIS WILL GET UPLOADED AS astropy

  version: '1.0.11'
  setup_options: '--offline --single-version-externally-managed --record=foo.txt'
  numpy_compiled_extensions: true

  # Continuum isn't building LTS at all now, so do this on py2 and py3.
  python: '2.7*|3.5*'

  # Since we only need these for CI, only build on linux.
  excluded_platforms:
    - 'win-64'
    - 'osx-64'
