# Adapted from the recipe at https://github.com/ContinuumIO/anaconda-recipes/blob/master/astropy/meta.yaml

# The lower limit on numpy should be whatever is appropriate for the latest
# astropy stable (i.e. non-LTS) release. The upper limit should be whatever
# numpy version continuum is already building astropy for.
{% set numpy_varsion_spec = ">=1.9,<1.12" %}

package:
  name: astropy
  version: {{ version }}

source:
  fn: astropy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/astropy/astropy-{{ version }}.tar.gz

build:
  entry_points:
    - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
    - fitscheck = astropy.io.fits.scripts.fitscheck:main
    - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
    - fitsheader = astropy.io.fits.scripts.fitsheader:main
    - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
    - samp_hub = astropy.samp.hub_script:hub_script
    - volint = astropy.io.votable.volint:main
    - wcslint = astropy.wcs.wcslint:main

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - numpy {{ numpy_varsion_spec }}
  run:
    - python
    - numpy x.x
    - numpy {{ numpy_varsion_spec }}
test:
  # Just a couple of sample imports/scripts here. Not meant to be exhaustive...
  commands:
    - fits2bitmap --help
    - fitscheck --help
    - fitsdiff --help
    - fitsheader --help
    - fitsinfo --help
    - samp_hub --help
    - volint --help
    - wcslint --help
  imports:
    - astropy
    - astropy.io.fits
    - astropy.time

about:
  home: http://www.astropy.org/
  license: BSD 3-clause
  summary: Community-developed Python Library for Astronomy
  doc_url: http://docs.astropy.org/en/stable/
  dev_url: https://github.com/astropy/astropy
