{% set version = "1.21.1" %}

package:
  name: conda-build
  version: {{ version }}.mod

source:
  url: https://github.com/conda/conda-build/archive/{{ version }}.tar.gz
  patches:
    - conda-build.patch

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - psutil
    - conda  >=4.1
    - jinja2
    - patchelf      [linux]

test:
  requires:
    - pytest
    - pytest-cov
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD
